# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e170d030b0e850698d117882927520387d27118d671ea86a5368c3a263b7e082fa0e2d2597b3602de128a4964bfd4750db429d0300639efd934f53d47aac2691

test:
  secret_key_base: 454d74fc93d53f41ca467603d3e41b35fc1b99de6973567b0e53449faf974be87fba195233f17cd27f90c95b13ab662061411fc083d86c33741bf8423aaa1840

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
